👷(ci) add CHANGELOG.md check to ci

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -9,6 +9,22 @@ on:
       - "*"
 
 jobs:
+  check-changelog:
+    runs-on: ubuntu-latest
+    if: ${{ github.event_name == 'pull_request' && github.actor != 'dependabot[bot]' }}
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+
+      - name: check if changelog is updated
+        run: |
+          if ! git diff --name-only origin/main | grep -q '^CHANGELOG.md$'; then
+            echo "Error: CHANGELOG.md must be updated for PRs."
+            exit 1
+          fi
+
   lint-commit-messages:
     runs-on: ubuntu-latest
     if: github.event_name == 'pull_request'
@@ -143,6 +159,7 @@ jobs:
     runs-on: ubuntu-latest
     needs:
       [
+        check-changelog,
         lint-commit-messages,
         check-format-rules,
         render-helmfile,
